version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gosec
    - unconvert
    - goconst
    - copyloopvar
    - clickhouselint
  settings:
    goconst:
      ignore-tests: true
      ignore-string-values:
        - "[A-Z]+"
    gosec:
      excludes:
        - G204
formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
  settings:
    goimports:
      # Put imports beginning with prefix after 3rd-party packages.
      local-prefixes:
        - github.com/ClickHouse/terraform-provider-clickhousedbops

run:
  timeout: 10m
