name: Shellcheck

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  shellcheck:
    runs-on: k8s-nano
    name: Shellcheck
    steps:
      - name: Checkout repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - name: Run
        run: |
          for FILE in $(find .github/actions -name '*.sh'); do
            echo "Running shellchek for ${FILE}"
            shellcheck "${FILE}"
          done
