name: Update grants from ClickHouse core

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  update_grants:
    runs-on: k8s-small
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.WORKFLOW_AUTH_PUBLIC_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_AUTH_PUBLIC_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run generate
        run: make generate

      - name: Check for changes
        id: diff
        run: |
          git diff internal/grants/grants.tsv
          if ! git diff-index --quiet HEAD -- internal/grants/grants.tsv; then
            echo "push_pr=true" >> "$GITHUB_OUTPUT"
          else
            echo "push_pr=false" >> "$GITHUB_OUTPUT"
          fi
          echo "branch=chore/update-grants-$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        if: steps.diff.outputs.push_pr == 'true'
        with:
          token: ${{ steps.generate-token.outputs.token }}
          add-paths: |
            internal/grants/grants.tsv
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          commit-message: "chore: update grants from ClickHouse core code"
          branch: ${{ steps.diff.outputs.branch }}
          title: "chore: update grants from ClickHouse core code"
          base: main
          body: |
            This PR updates grants from the ClickHouse core code.

            Command used: `make generate`

            Automatically generated by the update-grants workflow.
